<?php
/**
 * --- DO NOT EDIT THIS FILE ---
 * This file is generated automatically
 * and will replaced automatically by pukoconsole
 */

namespace plugins\model\primary;

use pukoframework\pda\Model;

/**
 * #DatabaseType mysql
 * #Table digital_signs
 * #PrimaryKey id
 */
class digital_signs extends Model
{

    
    /**
     * #Column id int(11) not null auto_increment
     */
    var $id = 0;

    /**
     * #Column user_id varchar(250)  
     */
    var $user_id = '';

    /**
     * #Column created datetime not null 
     */
    var $created = null;

    /**
     * #Column modified timestamp  on update current_timestamp()
     */
    var $modified = null;

    /**
     * #Column cuid int(11) not null 
     */
    var $cuid = 0;

    /**
     * #Column muid int(11) not null 
     */
    var $muid = 0;

    /**
     * #Column dflag tinyint(1) not null 
     */
    var $dflag = 0;

    /**
     * #Column document_name varchar(250)  
     */
    var $document_name = '';

    /**
     * #Column digital_sign_hash varchar(40)  
     */
    var $digital_sign_hash = '';

    /**
     * #Column digital_sign_secure varchar(8)  
     */
    var $digital_sign_secure = '';

    /**
     * #Column email varchar(250) not null 
     */
    var $email = '';

    /**
     * #Column location varchar(180) not null 
     */
    var $location = '';

    /**
     * #Column reason varchar(250) not null 
     */
    var $reason = '';


}
