<?php
/**
 * --- DO NOT EDIT THIS FILE ---
 * This file is generated automatically
 * and will replaced automatically by pukoconsole
 */

namespace plugins\model\primary;

use pukoframework\pda\Model;

/**
 * #DatabaseType mysql
 * #Table digital_sign_users
 * #PrimaryKey id
 */
class digital_sign_users extends Model
{

    
    /**
     * #Column id int(11) not null auto_increment
     */
    var $id = 0;

    /**
     * #Column user_id int(11)  
     */
    var $user_id = 0;

    /**
     * #Column created datetime not null 
     */
    var $created = null;

    /**
     * #Column modified timestamp not null on update current_timestamp()
     */
    var $modified = null;

    /**
     * #Column cuid int(11) not null 
     */
    var $cuid = 0;

    /**
     * #Column muid int(11) not null 
     */
    var $muid = 0;

    /**
     * #Column dflag tinyint(1) not null 
     */
    var $dflag = 0;

    /**
     * #Column name varchar(180) not null 
     */
    var $name = '';

    /**
     * #Column phone varchar(40) not null 
     */
    var $phone = '';

    /**
     * #Column email varchar(180) not null 
     */
    var $email = '';

    /**
     * #Column type varchar(60) not null 
     */
    var $type = '';

    /**
     * #Column ktp varchar(20) not null 
     */
    var $ktp = '';

    /**
     * #Column npwp varchar(20) not null 
     */
    var $npwp = '';

    /**
     * #Column address varchar(200) not null 
     */
    var $address = '';

    /**
     * #Column city varchar(100) not null 
     */
    var $city = '';

    /**
     * #Column province varchar(100) not null 
     */
    var $province = '';

    /**
     * #Column gender varchar(1) not null 
     */
    var $gender = '';

    /**
     * #Column place_of_birth varchar(100)  
     */
    var $place_of_birth = '';

    /**
     * #Column date_of_birth date  
     */
    var $date_of_birth = null;

    /**
     * #Column org_unit varchar(50)  
     */
    var $org_unit = '';

    /**
     * #Column work_unit varchar(50)  
     */
    var $work_unit = '';

    /**
     * #Column position varchar(100) not null 
     */
    var $position = '';

    /**
     * #Column is_verified tinyint(1)  
     */
    var $is_verified = 0;

    /**
     * #Column callback_url varchar(250)  
     */
    var $callback_url = '';

    /**
     * #Column is_speciment tinyint(1)  
     */
    var $is_speciment = 0;


}
