<?php
/**
 * --- DO NOT EDIT THIS FILE ---
 * This file is generated automatically
 * and will replaced automatically by pukoconsole
 */

namespace plugins\model\primary;

use pukoframework\pda\Model;

/**
 * #DatabaseType mysql
 * #Table feedback
 * #PrimaryKey id
 */
class feedback extends Model
{

    
    /**
     * #Column id int(11) not null auto_increment
     */
    var $id = 0;

    /**
     * #Column created datetime not null 
     */
    var $created = null;

    /**
     * #Column modified timestamp not null on update current_timestamp()
     */
    var $modified = null;

    /**
     * #Column cuid int(11) not null 
     */
    var $cuid = 0;

    /**
     * #Column muid int(11) not null 
     */
    var $muid = 0;

    /**
     * #Column dflag tinyint(1) not null 
     */
    var $dflag = 0;

    /**
     * #Column user_id int(11) not null 
     */
    var $user_id = 0;

    /**
     * #Column signature varchar(255) not null 
     */
    var $signature = '';

    /**
     * #Column subject varchar(255) not null 
     */
    var $subject = '';

    /**
     * #Column feedback text not null 
     */
    var $feedback = '';

    /**
     * #Column is_approved tinyint(1)  
     */
    var $is_approved = 0;

    /**
     * #Column approved_date datetime  
     */
    var $approved_date = null;

    /**
     * #Column feedback_responds text  
     */
    var $feedback_responds = '';


}
