<?php
/**
 * --- DO NOT EDIT THIS FILE ---
 * This file is generated automatically
 * and will replaced automatically by pukoconsole
 */

namespace plugins\model\primary;

use pukoframework\pda\Model;

/**
 * #DatabaseType mysql
 * #Table log_word
 * #PrimaryKey id
 */
class log_word extends Model
{


    /**
     * #Column id int(11) not null auto_increment
     */
    var $id = 0;

    /**
     * #Column word_id int(11)
     */
    var $word_id = 0;

    /**
     * #Column user_id int(11)
     */
    var $user_id = 0;

    /**
     * #Column sent_at timestamp not null on update current_timestamp()
     */
    var $sent_at = null;

    /**
     * #Column json_data longblob
     */
    var $json_data = null;

    /**
     * #Column creator_info text
     */
    var $creator_info = '';

    /**
     * #Column processing_time text
     */
    var $processing_time = '';

    /**
     * #Column created datetime not null
     */
    var $created = null;

    /**
     * #Column modified timestamp not null
     */
    var $modified = null;

    /**
     * #Column cuid int(11) not null
     */
    var $cuid = 0;

    /**
     * #Column muid int(11) not null
     */
    var $muid = 0;

    /**
     * #Column dflag tinyint(1) not null
     */
    var $dflag = 0;


}
