<?php
/**
 * --- DO NOT EDIT THIS FILE ---
 * This file is generated automatically
 * and will replaced automatically by pukoconsole
 */

namespace plugins\model\primary;

use pukoframework\pda\Model;

/**
 * #DatabaseType mysql
 * #Table mail
 * #PrimaryKey id
 */
class mail extends Model
{

    
    /**
     * #Column id int(11) not null auto_increment
     */
    var $id = 0;

    /**
     * #Column created datetime not null 
     */
    var $created = null;

    /**
     * #Column modified timestamp not null on update current_timestamp()
     */
    var $modified = null;

    /**
     * #Column cuid int(11) not null 
     */
    var $cuid = 0;

    /**
     * #Column muid int(11) not null 
     */
    var $muid = 0;

    /**
     * #Column dflag tinyint(1) not null 
     */
    var $dflag = 0;

    /**
     * #Column user_id int(11) not null 
     */
    var $user_id = 0;

    /**
     * #Column html text  
     */
    var $html = '';

    /**
     * #Column css text  
     */
    var $css = '';

    /**
     * #Column mail_name varchar(255) not null 
     */
    var $mail_name = '';

    /**
     * #Column mail_address varchar(255)  
     */
    var $mail_address = '';

    /**
     * #Column mail_password varchar(255)  
     */
    var $mail_password = '';

    /**
     * #Column cc varchar(255)  
     */
    var $cc = '';

    /**
     * #Column bcc varchar(255)  
     */
    var $bcc = '';

    /**
     * #Column reply_to varchar(255)  
     */
    var $reply_to = '';

    /**
     * #Column host varchar(255) not null 
     */
    var $host = '';

    /**
     * #Column port int(8) not null 
     */
    var $port = 0;

    /**
     * #Column smtp_auth varchar(20) not null 
     */
    var $smtp_auth = '';

    /**
     * #Column smtp_secure varchar(20) not null 
     */
    var $smtp_secure = '';

    /**
     * #Column request_type varchar(20) not null 
     */
    var $request_type = '';

    /**
     * #Column request_url varchar(155)  
     */
    var $request_url = '';

    /**
     * #Column request_sample text  
     */
    var $request_sample = '';

    /**
     * #Column css_external text  
     */
    var $css_external = '';


}
