<?php
/**
 * --- DO NOT EDIT THIS FILE ---
 * This file is generated automatically
 * and will replaced automatically by pukoconsole
 */

namespace plugins\model\primary;

use pukoframework\pda\Model;

/**
 * #DatabaseType mysql
 * #Table pdf
 * #PrimaryKey id
 */
class pdf extends Model
{

    
    /**
     * #Column id int(11) not null auto_increment
     */
    var $id = 0;

    /**
     * #Column created datetime not null 
     */
    var $created = null;

    /**
     * #Column modified timestamp not null on update current_timestamp()
     */
    var $modified = null;

    /**
     * #Column cuid int(11) not null 
     */
    var $cuid = 0;

    /**
     * #Column muid int(11) not null 
     */
    var $muid = 0;

    /**
     * #Column dflag tinyint(1) not null 
     */
    var $dflag = 0;

    /**
     * #Column user_id int(11) not null 
     */
    var $user_id = 0;

    /**
     * #Column report_name varchar(255) not null 
     */
    var $report_name = '';

    /**
     * #Column html longblob  
     */
    var $html = null;

    /**
     * #Column css longblob  
     */
    var $css = null;

    /**
     * #Column php_script longblob  
     */
    var $php_script = null;

    /**
     * #Column output_mode varchar(255) not null 
     */
    var $output_mode = '';

    /**
     * #Column paper varchar(255) not null 
     */
    var $paper = '';

    /**
     * #Column orientation varchar(30)  
     */
    var $orientation = '';

    /**
     * #Column request_type varchar(255)  
     */
    var $request_type = '';

    /**
     * #Column request_url varchar(255)  
     */
    var $request_url = '';

    /**
     * #Column request_sample text  
     */
    var $request_sample = '';

    /**
     * #Column css_external text  
     */
    var $css_external = '';


}
