<?php
/**
 * --- DO NOT EDIT THIS FILE ---
 * This file is generated automatically
 * and will replaced automatically by pukoconsole
 */

namespace plugins\model\primary;

use pukoframework\pda\Model;

/**
 * #DatabaseType mysql
 * #Table testimonial
 * #PrimaryKey id
 */
class testimonial extends Model
{

    
    /**
     * #Column id int(11) not null auto_increment
     */
    var $id = 0;

    /**
     * #Column created datetime not null 
     */
    var $created = null;

    /**
     * #Column modified timestamp not null on update current_timestamp()
     */
    var $modified = null;

    /**
     * #Column cuid int(11) not null 
     */
    var $cuid = 0;

    /**
     * #Column muid int(11) not null 
     */
    var $muid = 0;

    /**
     * #Column dflag tinyint(1) not null 
     */
    var $dflag = 0;

    /**
     * #Column user_id int(11) not null 
     */
    var $user_id = 0;

    /**
     * #Column signature varchar(255) not null 
     */
    var $signature = '';

    /**
     * #Column subject varchar(255) not null 
     */
    var $subject = '';

    /**
     * #Column testimonial text not null 
     */
    var $testimonial = '';

    /**
     * #Column is_valid tinyint(4)  
     */
    var $is_valid = 0;

    /**
     * #Column validation_date datetime  
     */
    var $validation_date = null;


}
