<?php
/**
 * --- DO NOT EDIT THIS FILE ---
 * This file is generated automatically
 * and will replaced automatically by pukoconsole
 */

namespace plugins\model\primary;

use pukoframework\pda\Model;

/**
 * #DatabaseType mysql
 * #Table users
 * #PrimaryKey id
 */
class users extends Model
{

    
    /**
     * #Column id int(11) not null auto_increment
     */
    var $id = 0;

    /**
     * #Column created datetime not null 
     */
    var $created = null;

    /**
     * #Column modified timestamp not null on update current_timestamp()
     */
    var $modified = null;

    /**
     * #Column cuid int(11) not null 
     */
    var $cuid = 0;

    /**
     * #Column muid int(11) not null 
     */
    var $muid = 0;

    /**
     * #Column dflag tinyint(1) not null 
     */
    var $dflag = 0;

    /**
     * #Column status_id int(11) not null 
     */
    var $status_id = 0;

    /**
     * #Column name varchar(100) not null 
     */
    var $name = '';

    /**
     * #Column username varchar(60) not null 
     */
    var $username = '';

    /**
     * #Column password varchar(200) not null 
     */
    var $password = '';

    /**
     * #Column email varchar(100) not null 
     */
    var $email = '';

    /**
     * #Column api_key varchar(80) not null 
     */
    var $api_key = '';


}
