<?php
/**
 * --- DO NOT EDIT THIS FILE ---
 * This file is generated automatically
 * and will replaced automatically by pukoconsole
 */

namespace plugins\model\primary;

use pukoframework\pda\Model;

/**
 * #DatabaseType mysql
 * #Table word
 * #PrimaryKey id
 */
class word extends Model
{

    
    /**
     * #Column id int(11) not null auto_increment
     */
    var $id = 0;

    /**
     * #Column user_id varchar(250)  
     */
    var $user_id = '';

    /**
     * #Column word_name varchar(255)  
     */
    var $word_name = '';

    /**
     * #Column html longblob  
     */
    var $html = null;

    /**
     * #Column css longblob  
     */
    var $css = null;

    /**
     * #Column php_script longblob  
     */
    var $php_script = null;

    /**
     * #Column request_type varchar(60)  
     */
    var $request_type = '';

    /**
     * #Column created datetime not null 
     */
    var $created = null;

    /**
     * #Column modified timestamp not null on update current_timestamp()
     */
    var $modified = null;

    /**
     * #Column cuid int(11) not null 
     */
    var $cuid = 0;

    /**
     * #Column muid int(11) not null 
     */
    var $muid = 0;

    /**
     * #Column dflag tinyint(1) not null 
     */
    var $dflag = 0;


}
